# Generated by Django 6.0.2 on 2026-03-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contatto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('oggetto', models.CharField(max_length=200)),
                ('messaggio', models.TextField()),
                ('data_invio', models.DateTimeField(auto_now_add=True)),
                ('letto', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Messaggi Contatti',
            },
        ),
        migrations.CreateModel(
            name='PosizioneLavorativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('dipartimento', models.CharField(max_length=100)),
                ('descrizione', models.TextField()),
                ('requisiti', models.TextField()),
                ('data_pubblicazione', models.DateField(auto_now_add=True)),
                ('attiva', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Posizioni Lavorative (Lavora con noi)',
            },
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.TextField()),
                ('icona', models.ImageField(blank=True, null=True, upload_to='tecnologie/')),
                ('ordine', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Tecnologie',
                'ordering': ['ordine'],
            },
        ),
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descrizione_breve', models.CharField(max_length=255)),
                ('descrizione_dettagliata', models.TextField()),
                ('prezzo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('immagine', models.ImageField(upload_to='prodotti/')),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('tecnologie_utilizzate', models.ManyToManyField(related_name='prodotti', to='core.tecnologia')),
            ],
            options={
                'verbose_name_plural': 'Prodotti',
            },
        ),
    ]
